/-
Erdős #866, Campaign 2, P1 — block certificate for h₄(n) ≤ 1000 (NEW module).

Machine-generated by lenses/P1-lean-h4-1000/gen_cert.py from
lenses/central-interval/data/cert_energy.csv (157 blocks tiling t ∈ [0, 400000]).
Every numeric conjunct is re-checked by the Lean kernel (`decide`); the
generator's own exact-integer pre-check is independent of the lens checker.

Shape of the certificate (PROOF.md §7, central-interval lens): for the block
containing t, the tuple (t2, ΦL, νL, ψL, ΦH, νH, ψH) satisfies
  (V2)  (N₀L+νL-1)(3ΦL+νL-1) < ΦL²νL   with N₀L = 4t2+2  (so 4*t2+1+νL form)
  (V3)  same with N₀H = 2t2+2
  (V4)  2·(8t2+2)·(ΦL-1) < ψL(ψL-1)  and  2·(4t2+2)·(ΦH-1) < ψH(ψH-1)
  (V5)  ψL + ψH ≤ 1001 + t.
-/
import Mathlib

set_option maxHeartbeats 1600000 in
/-- Block-certificate lookup: for every t ≤ 400000 there is a certified tuple
(t2, ΦL, νL, ψL, ΦH, νH, ψH) witnessing the energy violations (V2),(V3), the
popularity thresholds (V4), and the surplus bound (V5) for C = 1000. -/
lemma cert_lookup (t : ℕ) (ht : t ≤ 400000) :
    ∃ t2 ΦL νL ψL ΦH νH ψH : ℕ,
      t ≤ t2 ∧ 0 < ΦL ∧ 0 < νL ∧ 0 < ΦH ∧ 0 < νH ∧
      (4*t2 + 1 + νL) * (3*ΦL + νL - 1) < ΦL*ΦL*νL ∧
      (2*t2 + 1 + νH) * (3*ΦH + νH - 1) < ΦH*ΦH*νH ∧
      2*(8*t2+2)*(ΦL-1) < ψL*(ψL-1) ∧
      2*(4*t2+2)*(ΦH-1) < ψH*(ψH-1) ∧
      ψL + ψH ≤ 1001 + t := by
  by_cases h0 : t ≤ 444
  · exact ⟨444, 55, 542, 621, 41, 336, 378, h0, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h1 : t ≤ 743
  · exact ⟨743, 69, 792, 900, 51, 482, 546, h1, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h2 : t ≤ 959
  · exact ⟨959, 78, 1008, 1088, 57, 580, 657, h2, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h3 : t ≤ 1129
  · exact ⟨1129, 83, 1062, 1218, 62, 700, 743, h3, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h4 : t ≤ 1261
  · exact ⟨1261, 88, 1218, 1326, 65, 754, 805, h4, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h5 : t ≤ 1377
  · exact ⟨1377, 91, 1250, 1409, 67, 768, 854, h5, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h6 : t ≤ 1474
  · exact ⟨1474, 94, 1330, 1482, 69, 803, 897, h6, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h7 : t ≤ 1558
  · exact ⟨1558, 96, 1348, 1540, 71, 856, 935, h7, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h8 : t ≤ 1635
  · exact ⟨1635, 98, 1386, 1594, 72, 849, 965, h8, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h9 : t ≤ 1696
  · exact ⟨1696, 100, 1458, 1640, 74, 931, 996, h9, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h10 : t ≤ 1747
  · exact ⟨1747, 101, 1456, 1673, 74, 880, 1011, h10, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h11 : t ≤ 1800
  · exact ⟨1800, 103, 1550, 1715, 75, 900, 1033, h11, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h12 : t ≤ 1850
  · exact ⟨1850, 104, 1552, 1747, 76, 924, 1055, h12, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h13 : t ≤ 1896
  · exact ⟨1896, 105, 1563, 1777, 77, 954, 1075, h13, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h14 : t ≤ 1937
  · exact ⟨1937, 106, 1586, 1805, 78, 988, 1093, h14, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h15 : t ≤ 1971
  · exact ⟨1971, 107, 1622, 1829, 79, 1032, 1110, h15, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h16 : t ≤ 2004
  · exact ⟨2004, 108, 1662, 1853, 79, 998, 1119, h16, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h17 : t ≤ 2028
  · exact ⟨2028, 109, 1722, 1873, 80, 1052, 1133, h17, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h18 : t ≤ 2061
  · exact ⟨2061, 109, 1656, 1888, 80, 1019, 1142, h18, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h19 : t ≤ 2083
  · exact ⟨2083, 110, 1720, 1907, 81, 1076, 1156, h19, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h20 : t ≤ 2109
  · exact ⟨2109, 110, 1667, 1919, 81, 1050, 1163, h20, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h21 : t ≤ 2137
  · exact ⟨2137, 111, 1720, 1940, 81, 1022, 1171, h21, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h22 : t ≤ 2153
  · exact ⟨2153, 112, 1798, 1957, 82, 1086, 1182, h22, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h23 : t ≤ 2175
  · exact ⟨2175, 112, 1754, 1967, 82, 1064, 1188, h23, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h24 : t ≤ 2194
  · exact ⟨2194, 112, 1716, 1975, 82, 1045, 1193, h24, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h25 : t ≤ 2210
  · exact ⟨2210, 113, 1795, 1991, 83, 1110, 1205, h25, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h26 : t ≤ 2233
  · exact ⟨2233, 113, 1749, 2001, 83, 1088, 1211, h26, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h27 : t ≤ 2251
  · exact ⟨2251, 114, 1826, 2018, 83, 1069, 1216, h27, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h28 : t ≤ 2266
  · exact ⟨2266, 114, 1795, 2025, 84, 1136, 1228, h28, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h29 : t ≤ 2281
  · exact ⟨2281, 114, 1765, 2032, 84, 1122, 1232, h29, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h30 : t ≤ 2295
  · exact ⟨2295, 115, 1850, 2047, 84, 1107, 1236, h30, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h31 : t ≤ 2316
  · exact ⟨2316, 115, 1808, 2056, 84, 1086, 1241, h31, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h32 : t ≤ 2325
  · exact ⟨2325, 115, 1790, 2060, 85, 1160, 1251, h32, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h33 : t ≤ 2334
  · exact ⟨2334, 116, 1886, 2073, 85, 1152, 1254, h33, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h34 : t ≤ 2347
  · exact ⟨2347, 116, 1860, 2079, 85, 1138, 1257, h34, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h35 : t ≤ 2365
  · exact ⟨2365, 116, 1824, 2087, 85, 1120, 1262, h35, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h36 : t ≤ 2378
  · exact ⟨2378, 117, 1914, 2102, 85, 1107, 1265, h36, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h37 : t ≤ 2386
  · exact ⟨2386, 117, 1898, 2105, 86, 1184, 1275, h37, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h38 : t ≤ 2397
  · exact ⟨2397, 117, 1875, 2110, 86, 1172, 1278, h38, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h39 : t ≤ 2413
  · exact ⟨2413, 117, 1843, 2117, 86, 1156, 1282, h39, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h40 : t ≤ 2422
  · exact ⟨2422, 118, 1941, 2130, 86, 1147, 1284, h40, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h41 : t ≤ 2435
  · exact ⟨2435, 118, 1915, 2136, 86, 1134, 1288, h41, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h42 : t ≤ 2447
  · exact ⟨2447, 118, 1891, 2141, 86, 1122, 1291, h42, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h43 : t ≤ 2460
  · exact ⟨2460, 118, 1865, 2147, 87, 1194, 1302, h43, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h44 : t ≤ 2465
  · exact ⟨2465, 119, 1972, 2158, 87, 1189, 1303, h44, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h45 : t ≤ 2472
  · exact ⟨2472, 119, 1958, 2161, 87, 1182, 1305, h45, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h46 : t ≤ 2483
  · exact ⟨2483, 119, 1936, 2166, 87, 1171, 1308, h46, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h47 : t ≤ 2499
  · exact ⟨2499, 119, 1904, 2173, 87, 1155, 1312, h47, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h48 : t ≤ 2508
  · exact ⟨2508, 120, 2004, 2186, 87, 1146, 1315, h48, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h49 : t ≤ 2511
  · exact ⟨2511, 120, 1998, 2188, 87, 1144, 1316, h49, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h50 : t ≤ 2515
  · exact ⟨2515, 120, 1990, 2189, 88, 1226, 1324, h50, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h51 : t ≤ 2520
  · exact ⟨2520, 120, 1980, 2192, 88, 1220, 1325, h51, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h52 : t ≤ 2527
  · exact ⟨2527, 120, 1966, 2195, 88, 1213, 1327, h52, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h53 : t ≤ 2538
  · exact ⟨2538, 120, 1944, 2199, 88, 1202, 1330, h53, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h54 : t ≤ 2552
  · exact ⟨2552, 120, 1916, 2205, 88, 1188, 1334, h54, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h55 : t ≤ 2560
  · exact ⟨2560, 121, 2019, 2218, 88, 1180, 1336, h55, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h56 : t ≤ 2572
  · exact ⟨2572, 121, 1995, 2223, 88, 1168, 1339, h56, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h57 : t ≤ 2578
  · exact ⟨2578, 121, 1984, 2226, 89, 1250, 1348, h57, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h58 : t ≤ 2586
  · exact ⟨2586, 121, 1968, 2229, 89, 1242, 1350, h58, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h59 : t ≤ 2597
  · exact ⟨2597, 121, 1945, 2234, 89, 1230, 1353, h59, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h60 : t ≤ 2601
  · exact ⟨2601, 122, 2058, 2245, 89, 1226, 1354, h60, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h61 : t ≤ 2606
  · exact ⟨2606, 122, 2048, 2247, 89, 1221, 1356, h61, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h62 : t ≤ 2613
  · exact ⟨2613, 122, 2034, 2250, 89, 1214, 1357, h62, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h63 : t ≤ 2624
  · exact ⟨2624, 122, 2011, 2255, 89, 1203, 1360, h63, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h64 : t ≤ 2640
  · exact ⟨2640, 122, 1979, 2262, 89, 1187, 1364, h64, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h65 : t ≤ 2646
  · exact ⟨2646, 122, 1968, 2264, 90, 1269, 1374, h65, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h66 : t ≤ 2647
  · exact ⟨2647, 123, 2086, 2274, 90, 1268, 1374, h66, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h67 : t ≤ 2649
  · exact ⟨2649, 123, 2082, 2275, 90, 1266, 1374, h67, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h68 : t ≤ 2652
  · exact ⟨2652, 123, 2076, 2276, 90, 1264, 1375, h68, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h69 : t ≤ 2656
  · exact ⟨2656, 123, 2068, 2278, 90, 1259, 1376, h69, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h70 : t ≤ 2661
  · exact ⟨2661, 123, 2058, 2280, 90, 1254, 1378, h70, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h71 : t ≤ 2668
  · exact ⟨2668, 123, 2044, 2283, 90, 1248, 1379, h71, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h72 : t ≤ 2680
  · exact ⟨2680, 123, 2020, 2288, 90, 1235, 1382, h72, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h73 : t ≤ 2694
  · exact ⟨2694, 123, 1992, 2294, 90, 1221, 1386, h73, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h74 : t ≤ 2703
  · exact ⟨2703, 124, 2096, 2308, 90, 1212, 1388, h74, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h75 : t ≤ 2707
  · exact ⟨2707, 124, 2088, 2309, 90, 1208, 1389, h75, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h76 : t ≤ 2712
  · exact ⟨2712, 124, 2078, 2311, 91, 1292, 1398, h76, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h77 : t ≤ 2719
  · exact ⟨2719, 124, 2064, 2314, 91, 1285, 1400, h77, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h78 : t ≤ 2728
  · exact ⟨2728, 124, 2046, 2318, 91, 1276, 1403, h78, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h79 : t ≤ 2742
  · exact ⟨2742, 124, 2018, 2324, 91, 1262, 1406, h79, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h80 : t ≤ 2749
  · exact ⟨2749, 125, 2128, 2336, 91, 1256, 1408, h80, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h81 : t ≤ 2758
  · exact ⟨2758, 125, 2109, 2340, 91, 1246, 1410, h81, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h82 : t ≤ 2772
  · exact ⟨2772, 125, 2082, 2346, 91, 1232, 1414, h82, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h83 : t ≤ 2782
  · exact ⟨2782, 125, 2061, 2350, 92, 1312, 1424, h83, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h84 : t ≤ 2790
  · exact ⟨2790, 125, 2045, 2354, 92, 1304, 1426, h84, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h85 : t ≤ 2794
  · exact ⟨2794, 126, 2161, 2365, 92, 1300, 1427, h85, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h86 : t ≤ 2799
  · exact ⟨2799, 126, 2152, 2367, 92, 1296, 1429, h86, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h87 : t ≤ 2807
  · exact ⟨2807, 126, 2136, 2370, 92, 1288, 1431, h87, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h88 : t ≤ 2818
  · exact ⟨2818, 126, 2113, 2375, 92, 1276, 1433, h88, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h89 : t ≤ 2835
  · exact ⟨2835, 126, 2080, 2382, 92, 1259, 1438, h89, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h90 : t ≤ 2843
  · exact ⟨2843, 127, 2188, 2395, 92, 1251, 1440, h90, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h91 : t ≤ 2846
  · exact ⟨2846, 127, 2182, 2396, 93, 1339, 1448, h91, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h92 : t ≤ 2850
  · exact ⟨2850, 127, 2174, 2398, 93, 1336, 1449, h92, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h93 : t ≤ 2858
  · exact ⟨2858, 127, 2158, 2401, 93, 1328, 1451, h93, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h94 : t ≤ 2869
  · exact ⟨2869, 127, 2136, 2406, 93, 1316, 1454, h94, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h95 : t ≤ 2885
  · exact ⟨2885, 127, 2104, 2413, 93, 1300, 1458, h95, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h96 : t ≤ 2894
  · exact ⟨2894, 128, 2212, 2426, 93, 1291, 1461, h96, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h97 : t ≤ 2909
  · exact ⟨2909, 128, 2182, 2432, 93, 1276, 1464, h97, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h98 : t ≤ 2918
  · exact ⟨2918, 128, 2164, 2436, 94, 1360, 1475, h98, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h99 : t ≤ 2933
  · exact ⟨2933, 128, 2134, 2442, 94, 1344, 1478, h99, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h100 : t ≤ 2941
  · exact ⟨2941, 129, 2245, 2455, 94, 1336, 1480, h100, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h101 : t ≤ 2953
  · exact ⟨2953, 129, 2221, 2460, 94, 1324, 1483, h101, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h102 : t ≤ 2970
  · exact ⟨2970, 129, 2187, 2467, 94, 1307, 1488, h102, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h103 : t ≤ 2984
  · exact ⟨2984, 129, 2160, 2473, 95, 1386, 1499, h103, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h104 : t ≤ 2990
  · exact ⟨2990, 130, 2275, 2485, 95, 1380, 1501, h104, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h105 : t ≤ 3000
  · exact ⟨3000, 130, 2256, 2489, 95, 1370, 1503, h105, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h106 : t ≤ 3014
  · exact ⟨3014, 130, 2227, 2495, 95, 1356, 1507, h106, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h107 : t ≤ 3036
  · exact ⟨3036, 130, 2184, 2504, 95, 1334, 1512, h107, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h108 : t ≤ 3053
  · exact ⟨3053, 131, 2278, 2521, 95, 1317, 1516, h108, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h109 : t ≤ 3068
  · exact ⟨3068, 131, 2248, 2527, 96, 1396, 1528, h109, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h110 : t ≤ 3090
  · exact ⟨3090, 131, 2204, 2536, 96, 1374, 1534, h110, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h111 : t ≤ 3109
  · exact ⟨3109, 132, 2296, 2554, 96, 1355, 1538, h111, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h112 : t ≤ 3125
  · exact ⟨3125, 132, 2264, 2560, 97, 1434, 1550, h112, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h113 : t ≤ 3142
  · exact ⟨3142, 132, 2230, 2567, 97, 1417, 1555, h113, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h114 : t ≤ 3162
  · exact ⟨3162, 133, 2322, 2585, 97, 1397, 1559, h114, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h115 : t ≤ 3191
  · exact ⟨3191, 133, 2264, 2597, 97, 1368, 1567, h115, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h116 : t ≤ 3209
  · exact ⟨3209, 134, 2360, 2614, 98, 1446, 1579, h116, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h117 : t ≤ 3236
  · exact ⟨3236, 134, 2306, 2625, 98, 1419, 1586, h117, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h118 : t ≤ 3263
  · exact ⟨3263, 135, 2384, 2646, 98, 1392, 1592, h118, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h119 : t ≤ 3291
  · exact ⟨3291, 135, 2328, 2657, 99, 1461, 1607, h119, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h120 : t ≤ 3320
  · exact ⟨3320, 136, 2404, 2679, 99, 1432, 1614, h120, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h121 : t ≤ 3352
  · exact ⟨3352, 136, 2340, 2692, 100, 1498, 1630, h121, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h122 : t ≤ 3386
  · exact ⟨3386, 137, 2408, 2715, 100, 1464, 1639, h122, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h123 : t ≤ 3419
  · exact ⟨3419, 138, 2477, 2739, 100, 1432, 1647, h123, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h124 : t ≤ 3461
  · exact ⟨3461, 138, 2393, 2755, 101, 1488, 1665, h124, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h125 : t ≤ 3498
  · exact ⟨3498, 139, 2456, 2780, 102, 1552, 1682, h125, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h126 : t ≤ 3541
  · exact ⟨3541, 140, 2508, 2807, 102, 1508, 1693, h126, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h127 : t ≤ 3580
  · exact ⟨3580, 141, 2570, 2833, 103, 1570, 1710, h127, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h128 : t ≤ 3627
  · exact ⟨3627, 141, 2475, 2851, 103, 1523, 1721, h128, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h129 : t ≤ 3683
  · exact ⟨3683, 142, 2504, 2884, 104, 1570, 1743, h129, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h130 : t ≤ 3739
  · exact ⟨3739, 143, 2532, 2916, 105, 1616, 1765, h130, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h131 : t ≤ 3803
  · exact ⟨3803, 145, 2689, 2961, 105, 1552, 1780, h131, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h132 : t ≤ 3875
  · exact ⟨3875, 146, 2689, 2999, 106, 1584, 1805, h132, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h133 : t ≤ 3962
  · exact ⟨3962, 147, 2660, 3043, 107, 1602, 1834, h133, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h134 : t ≤ 4052
  · exact ⟨4052, 149, 2773, 3099, 108, 1618, 1864, h134, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h135 : t ≤ 4147
  · exact ⟨4147, 150, 2731, 3145, 110, 1738, 1903, h135, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h136 : t ≤ 4265
  · exact ⟨4265, 152, 2794, 3211, 111, 1730, 1938, h136, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h137 : t ≤ 4390
  · exact ⟨4390, 154, 2848, 3279, 113, 1826, 1984, h137, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h138 : t ≤ 4537
  · exact ⟨4537, 157, 3016, 3366, 114, 1790, 2026, h138, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h139 : t ≤ 4704
  · exact ⟨4704, 159, 2994, 3450, 116, 1850, 2081, h139, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h140 : t ≤ 4898
  · exact ⟨4898, 162, 3083, 3553, 118, 1888, 2142, h140, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h141 : t ≤ 5128
  · exact ⟨5128, 166, 3274, 3680, 121, 2011, 2220, h141, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h142 : t ≤ 5403
  · exact ⟨5403, 170, 3389, 3823, 124, 2099, 2307, h142, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h143 : t ≤ 5740
  · exact ⟨5740, 175, 3570, 3999, 127, 2134, 2406, h143, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h144 : t ≤ 6155
  · exact ⟨6155, 181, 3800, 4211, 131, 2229, 2531, h144, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h145 : t ≤ 6677
  · exact ⟨6677, 188, 4036, 4471, 136, 2368, 2686, h145, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h146 : t ≤ 7366
  · exact ⟨7366, 196, 4182, 4795, 142, 2504, 2884, h146, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h147 : t ≤ 8281
  · exact ⟨8281, 207, 4552, 5225, 150, 2744, 3143, h147, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h148 : t ≤ 9532
  · exact ⟨9532, 221, 5026, 5794, 160, 3028, 3483, h148, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h149 : t ≤ 11309
  · exact ⟨11309, 240, 5822, 6577, 174, 3568, 3957, h149, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h150 : t ≤ 13987
  · exact ⟨13987, 265, 6741, 7687, 192, 4157, 4624, h150, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h151 : t ≤ 18280
  · exact ⟨18280, 301, 8290, 9368, 217, 4939, 5621, h151, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h152 : t ≤ 25714
  · exact ⟨25714, 354, 10699, 12052, 255, 6416, 7230, h152, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h153 : t ≤ 40004
  · exact ⟨40004, 437, 14821, 16706, 314, 8824, 10010, h153, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h154 : t ≤ 71407
  · exact ⟨71407, 576, 22210, 25632, 414, 13670, 15361, h154, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  by_cases h155 : t ≤ 153840
  · exact ⟨153840, 835, 39680, 45309, 597, 23469, 27084, h155, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
  exact ⟨400000, 1329, 81128, 92192, 948, 47930, 55050, ht, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by decide, by omega⟩
