# checker_a13.py -- clean-room Gate-4 checker for the refutation of Conjecture A.13 of
# arXiv:2412.16177v1 (Chuharski, Rojas Collins, Meringolo, "Mining Math Conjectures from
# LLMs: A Pruning Approach").
#
# Conjecture A.13 (verbatim, PDF p.60, section A.5.6 "Additional Conjectures"):
#   "Let G be a non-solvable group. For any element x in G, if SolG(x) is a proper
#    subgroup of G, then the intersection of SolG(x) with all of its conjugates in G
#    is always contained in the hypercenter of G."
# Definition 3.1 (verbatim): "Let G be a finite group. For any element x in G, the
#    solubilizer of x in G is defined as: SolG(x) := {y in G | <x,y> is soluble}".
# "Hypercenter" is not defined in the paper; the standard meaning is used: the terminal
# (stable) member Z_inf(G) of the upper central series Z_0=1 <= Z_1=Z(G) <= ... .
#
# Claimed counterexample: G = A5 x S3 (order 360), x = ((0 1 2 3 4), id).
# This checker rebuilds everything from scratch with exact integer/permutation
# arithmetic only (no floats, no external libraries) and verifies:
#   (1) G is a non-solvable group of order 360;
#   (2) Sol_G(x) is a *subgroup*, of order 60, proper in G;
#   (3) the normal core  K = intersection over g in G of g^-1 Sol_G(x) g  has order 6
#       and equals 1 x S3 (elements acting trivially on the A5 points);
#   (4) the upper central series of G stabilizes at the trivial group, i.e. the
#       hypercenter Z_inf(G) = 1;
#   (5) K is NOT contained in Z_inf(G)  ==> Conjecture A.13 is FALSE.
# Extension sweep: for EVERY x in G it computes Sol_G(x), tests subgroup-ness and
# properness, computes the core, and counts violations of A.13; it also confirms
# Sol_G(x^g) = g^-1 Sol_G(x) g (the two grammatical readings of "its conjugates"
# coincide) and that N = 1 x S3 is a solvable normal subgroup contained in every
# solubilizer (the structural reason the conjecture is doomed).
#
# Usage:
#   python checker_a13.py --emit cert.json    # recompute, assert, write certificate
#   python checker_a13.py --verify cert.json  # recompute, assert, compare to cert
# Exit code 0 + "ACCEPT" iff everything passes; nonzero + "REJECT: ..." otherwise.

import itertools, json, sys

# ----------------------------------------------------------------------------------
# permutations as tuples p of length 8: p[i] = image of point i.
# A5 acts on points 0..4 (even permutations); S3 acts on points 5..7.
# composition convention: (p*q)(i) = p[q[i]]  (apply q first) -- conventions do not
# affect any group-theoretic statement checked here.
# ----------------------------------------------------------------------------------

def compose(p, q):
    return tuple(p[q[i]] for i in range(len(p)))

def perm_parity(p):
    seen = [False] * len(p)
    par = 0
    for i in range(len(p)):
        if not seen[i]:
            j, clen = i, 0
            while not seen[j]:
                seen[j] = True
                j = p[j]
                clen += 1
            par ^= (clen - 1) & 1
    return par

def fail(msg):
    print("REJECT: " + msg)
    sys.exit(1)

# --- build G = A5 x S3 as permutations of {0..7} ----------------------------------
A5 = [p for p in itertools.permutations(range(5)) if perm_parity(p) == 0]
S3 = list(itertools.permutations(range(3)))
if len(A5) != 60 or len(S3) != 6:
    fail("component construction wrong: |A5|=%d |S3|=%d" % (len(A5), len(S3)))

elems = []
for a in A5:
    for b in S3:
        elems.append(tuple(list(a) + [5 + b[j] for j in range(3)]))
n = len(elems)
if n != 360:
    fail("|G| != 360")
idx = {p: i for i, p in enumerate(elems)}

# multiplication and inverse tables (closure of G under * is verified by idx lookups)
mult = [[0] * n for _ in range(n)]
for i in range(n):
    pi = elems[i]
    row = mult[i]
    for j in range(n):
        prod = compose(pi, elems[j])
        if prod not in idx:
            fail("G not closed under multiplication")
        row[j] = idx[prod]
E = idx[tuple(range(8))]
inv = [0] * n
for i in range(n):
    found = False
    for j in range(n):
        if mult[i][j] == E:
            inv[i] = j
            found = True
            break
    if not found:
        fail("element without inverse")

def comm(a, b):  # a^-1 b^-1 a b
    return mult[mult[mult[inv[a]][inv[b]]][a]][b]

def conj(g, s):  # g^-1 s g
    return mult[mult[inv[g]][s]][g]

def closure(gens):
    """subgroup generated by gens (indices); BFS over positive words (finite group,
    so positive words already form the subgroup)."""
    gens = sorted(set(gens))
    seen = {E}
    frontier = [E]
    while frontier:
        nxt = []
        for h in frontier:
            row = mult[h]
            for g in gens:
                x = row[g]
                if x not in seen:
                    seen.add(x)
                    nxt.append(x)
        frontier = nxt
    return frozenset(seen)

def derived_subgroup(H):
    Hl = list(H)
    comms = {comm(a, b) for a in Hl for b in Hl}
    return closure(comms)

_solvable_cache = {}
def is_solvable(H):
    """H solvable iff its derived series reaches {e}."""
    if H in _solvable_cache:
        return _solvable_cache[H]
    cur = H
    while True:
        d = derived_subgroup(cur)
        if d == cur:
            res = (cur == frozenset({E}))
            break
        cur = d
    _solvable_cache[H] = res
    return res

_pair_cache = {}
def gen2_solvable(x, y):
    key = (x, y) if x <= y else (y, x)
    if key in _pair_cache:
        return _pair_cache[key]
    res = is_solvable(closure([x, y]))
    _pair_cache[key] = res
    return res

_sol_cache = {}
def solubilizer(x):
    """Sol_G(x) computed directly; cached via the canonical cyclic subgroup <x>
    (if <x>=<x'> then <x,y>=<x',y> for all y, so Sol_G(x)=Sol_G(x'))."""
    cyc = closure([x])
    if cyc in _sol_cache:
        return _sol_cache[cyc]
    S = frozenset(y for y in range(n) if gen2_solvable(x, y))
    _sol_cache[cyc] = S
    return S

def is_subgroup(S):
    if E not in S:
        return False
    Sl = list(S)
    for a in Sl:
        row = mult[a]
        for b in Sl:
            if row[b] not in S:
                return False
    return True

def normal_core(S):
    """intersection over all g in G of g^-1 S g (S a subset of G)."""
    K = set(S)
    for g in range(n):
        K &= {conj(g, s) for s in S}
        if len(K) == 1:
            # keep going anyway (cheap) to stay literal; no early exit needed
            pass
    return frozenset(K)

def upper_central_series():
    Z = frozenset({E})
    series = [Z]
    while True:
        Znext = frozenset(z for z in range(n) if all(comm(z, g) in Z for g in range(n)))
        if Znext == Z:
            break
        Z = Znext
        series.append(Z)
    return series

def perm_of(i):
    return list(elems[i])

# ==================================================================================
def main():
    mode, certpath = None, None
    if len(sys.argv) == 3 and sys.argv[1] in ("--emit", "--verify"):
        mode, certpath = sys.argv[1], sys.argv[2]
    else:
        fail("usage: checker_a13.py --emit|--verify cert.json")

    log = []
    def say(s):
        log.append(s)
        print(s)

    # ---- (1) G non-solvable -------------------------------------------------------
    Gset = frozenset(range(n))
    dseries = [Gset]
    cur = Gset
    while True:
        d = derived_subgroup(cur)
        if d == cur:
            break
        cur = d
        dseries.append(cur)
    say("derived series of G orders: %s" % [len(t) for t in dseries])
    if cur == frozenset({E}):
        fail("G is solvable -- wrong group")
    if is_solvable(Gset):
        fail("solvability test inconsistent")
    say("(1) G = A5 x S3, |G| = 360, non-solvable (derived series stabilizes at order %d perfect subgroup)" % len(cur))

    # ---- (2) Sol_G(x) -------------------------------------------------------------
    a0 = (1, 2, 3, 4, 0)            # the 5-cycle 0->1->2->3->4->0
    x = idx[tuple(list(a0) + [5, 6, 7])]
    S = solubilizer(x)
    say("|Sol_G(x)| = %d" % len(S))
    if len(S) != 60:
        fail("expected |Sol_G(x)| = 60")
    if not is_subgroup(S):
        fail("Sol_G(x) is not a subgroup -- hypothesis of A.13 would not apply")
    if len(S) >= n:
        fail("Sol_G(x) is not proper")
    # structure check: projection to A5 part has order 10 (D10), S3 part full, S = product
    projA = {elems[s][:5] for s in S}
    projB = {elems[s][5:] for s in S}
    if len(projA) != 10 or len(projB) != 6 or len(S) != 60:
        fail("Sol_G(x) is not D10 x S3 shaped: |projA|=%d |projB|=%d" % (len(projA), len(projB)))
    say("(2) Sol_G(x) is a proper subgroup of order 60 = (order-10 subgroup of A5) x S3")

    # ---- (3) normal core ----------------------------------------------------------
    K = normal_core(S)
    say("|core| = %d, core = %s" % (len(K), sorted(perm_of(k) for k in K)))
    if len(K) != 6:
        fail("expected |core| = 6")
    if not is_subgroup(K):
        fail("core is not a subgroup")
    for g in range(n):
        if {conj(g, k) for k in K} != set(K):
            fail("core is not normal in G")
    if any(elems[k][:5] != (0, 1, 2, 3, 4) for k in K):
        fail("core has nontrivial A5 part -- expected 1 x S3")
    if not is_solvable(K):
        fail("core (= S3) should be solvable")
    say("(3) core of Sol_G(x) = 1 x S3, order 6, normal in G")

    # ---- (4) hypercenter ----------------------------------------------------------
    ucs = upper_central_series()
    say("upper central series orders: %s (stable)" % [len(t) for t in ucs])
    hyp = ucs[-1]
    if hyp != frozenset({E}):
        fail("hypercenter is nontrivial -- counterexample claim would be wrong")
    say("(4) Z(G) = 1, hypercenter Z_inf(G) = 1")

    # ---- (5) the kill --------------------------------------------------------------
    if K <= hyp:
        fail("core IS contained in hypercenter -- conjecture not refuted by this instance")
    witness = next(k for k in sorted(K) if k != E)
    say("(5) core (order 6) is NOT contained in hypercenter (order 1); witness element %s" % perm_of(witness))
    say("==> Conjecture A.13 is FALSE for G = A5 x S3, x = ((0 1 2 3 4), id).")

    # ---- extension sweep over every x in G -----------------------------------------
    n_proper_subgroup = 0
    n_violations = 0
    n_subgroup = 0
    Nfixed = K  # 1 x S3
    sol_sizes = {}
    reading_check_ok = True
    for xx in range(n):
        Sx = solubilizer(xx)
        sol_sizes[len(Sx)] = sol_sizes.get(len(Sx), 0) + 1
        if not Nfixed <= Sx:
            fail("solvable normal subgroup 1xS3 not inside Sol_G(%d)" % xx)
        if is_subgroup(Sx):
            n_subgroup += 1
            if len(Sx) < n:
                n_proper_subgroup += 1
                Kx = normal_core(Sx)
                if not (Kx <= hyp):
                    n_violations += 1
    # reading equivalence Sol_G(x^g) = g^-1 Sol_G(x) g  for the certificate x, all g
    for g in range(n):
        xg = conj(g, x)
        if solubilizer(xg) != frozenset(conj(g, s) for s in S):
            reading_check_ok = False
            break
    if not reading_check_ok:
        fail("Sol_G(x^g) != (Sol_G(x))^g -- reading equivalence broken")
    say("extension: Sol_G(x) sizes over all 360 x: %s" % dict(sorted(sol_sizes.items())))
    say("extension: #x with Sol a subgroup: %d; proper subgroup: %d; A.13 violated for ALL %d of them"
        % (n_subgroup, n_proper_subgroup, n_violations))
    if n_proper_subgroup == 0 or n_violations != n_proper_subgroup:
        fail("sweep inconsistency: proper=%d violations=%d" % (n_proper_subgroup, n_violations))
    say("extension: 1 x S3 (solvable, normal) lies in Sol_G(x) for every x; both readings of 'its conjugates' coincide")

    # ---- certificate ----------------------------------------------------------------
    cert = {
        "conjecture": "A.13, arXiv:2412.16177v1",
        "statement_verbatim": "Let G be a non-solvable group. For any element x in G, if SolG(x) is a proper subgroup of G, then the intersection of SolG(x) with all of its conjugates in G is always contained in the hypercenter of G.",
        "group": "A5 x S3 as permutations of {0..7}: A5 = even perms of {0..4}, S3 = perms of {5,6,7}; order 360",
        "x": perm_of(x),
        "sol_x": sorted(perm_of(s) for s in S),
        "sol_x_order": len(S),
        "sol_x_is_proper_subgroup": True,
        "core": sorted(perm_of(k) for k in K),
        "core_order": len(K),
        "upper_central_series_orders": [len(t) for t in ucs],
        "hypercenter": [perm_of(E)],
        "hypercenter_order": 1,
        "witness_in_core_not_in_hypercenter": perm_of(witness),
        "derived_series_of_G_orders": [len(t) for t in dseries],
        "G_nonsolvable": True,
        "sweep_all_x": {"sol_is_subgroup_count": n_subgroup,
                         "sol_proper_subgroup_count": n_proper_subgroup,
                         "a13_violation_count": n_violations},
        "conclusion": "core (order 6) is not contained in hypercenter (order 1): Conjecture A.13 is FALSE",
    }

    if mode == "--emit":
        with open(certpath, "w", encoding="utf-8") as f:
            json.dump(cert, f, indent=1)
        say("certificate written to %s" % certpath)
    else:  # --verify
        with open(certpath, encoding="utf-8") as f:
            given = json.load(f)
        for key in ["x", "sol_x", "sol_x_order", "core", "core_order",
                    "upper_central_series_orders", "hypercenter", "hypercenter_order",
                    "witness_in_core_not_in_hypercenter", "derived_series_of_G_orders",
                    "sweep_all_x", "statement_verbatim"]:
            if key not in given:
                fail("certificate missing field %r" % key)
            if given[key] != cert[key]:
                fail("certificate field %r does not match recomputation" % key)
        # semantic re-checks straight off the certificate data
        wt = given["witness_in_core_not_in_hypercenter"]
        if wt not in given["core"] or wt in given["hypercenter"]:
            fail("certificate witness not in core, or in hypercenter")
        if any(c in given["hypercenter"] for c in given["core"] if c != perm_of(E)) :
            fail("certificate core unexpectedly inside hypercenter")
        say("certificate %s matches independent recomputation" % certpath)

    say("ACCEPT")
    return log

if __name__ == "__main__":
    main()
