"""Orchestrator's independent verification of P2 harvester refutation claims.
All objects rebuilt from construction descriptions, not from agent edge lists."""
import itertools, math
from fractions import Fraction

ok = lambda b: "PASS" if b else "FAIL"

# ---------- 1. Davila Conjecture 9: Z(G) <= gamma(G)+2 for connected cubic diamond-free ----------
# Claimed kill: K3,3 # K3,3 bridge-sum, n=14: subdivide edge (0,3) -> 12, edge (6,9) -> 13, bridge 12-13.
E = set()
for a in (0,1,2):
    for b in (3,4,5):
        E.add((a,b))
for a in (6,7,8):
    for b in (9,10,11):
        E.add((a,b))
E.discard((0,3)); E.discard((6,9))
E |= {(0,12),(3,12),(6,13),(9,13),(12,13)}
n = 14
adj = [set() for _ in range(n)]
for a,b in E: adj[a].add(b); adj[b].add(a)

cubic = all(len(adj[v])==3 for v in range(n))
# connected
seen={0}; st=[0]
while st:
    v=st.pop()
    for w in adj[v]:
        if w not in seen: seen.add(w); st.append(w)
conn = len(seen)==n
# diamond-free (adjacent pair with >=2 common neighbors); also report triangle-free
diam_free = all(len(adj[a]&adj[b])<2 for a,b in E)
tri_free  = all(len(adj[a]&adj[b])==0 for a,b in E)

def dominates(S):
    cov=set(S)
    for v in S: cov|=adj[v]
    return len(cov)==n
g3 = any(dominates(S) for S in itertools.combinations(range(n),3))
g4 = any(dominates(S) for S in itertools.combinations(range(n),4))

def zf_closure(S):
    blue=set(S); changed=True
    while changed:
        changed=False
        for v in list(blue):
            white=[w for w in adj[v] if w not in blue]
            if len(white)==1: blue.add(white[0]); changed=True
    return blue
z6 = any(len(zf_closure(S))==n for S in itertools.combinations(range(n),6))
z7_witness = len(zf_closure({0,1,3,4,6,7,10}))==n
z7 = z7_witness or any(len(zf_closure(S))==n for S in itertools.combinations(range(n),7))

print(f"[C9] cubic={ok(cubic)} connected={ok(conn)} diamond-free={ok(diam_free)} (triangle-free={tri_free})")
print(f"[C9] gamma: no size-3 dom set={ok(not g3)}, size-4 exists={ok(g4)} -> gamma=4")
print(f"[C9] Z: no size-6 forcing set={ok(not z6)}, size-7 exists={ok(z7)} (their witness works: {z7_witness}) -> Z=7")
print(f"[C9] VERDICT: Z = gamma+3 -> Conjecture 9 REFUTED: {ok(cubic and conn and diam_free and not g3 and g4 and not z6 and z7)}")

# ---------- 2. LLM-solubilizer A.1: Sol_G(x) n Sol_G(y) contains nontrivial normal subgroup of G ----------
# Claimed kill: G=A5, x=y=5-cycle. Build A5, compute Sol(x), enumerate normal subgroups computationally.
perms = [p for p in itertools.permutations(range(5))]
def sgn(p):
    s=1
    for i in range(5):
        for j in range(i+1,5):
            if p[i]>p[j]: s=-s
    return s
A5 = [p for p in perms if sgn(p)==1]
mul = lambda p,q: tuple(p[q[i]] for i in range(5))
def subgroup(gens):
    H={tuple(range(5))}; frontier=list(H)
    while frontier:
        a=frontier.pop()
        for g in gens:
            b=mul(a,g)
            if b not in H: H.add(b); frontier.append(b)
    return H
def derived(H):
    Hl=list(H); inv={p: tuple(sorted(range(5), key=lambda i: p[i])) for p in H}
    # inverse: q with p[q[i]]=i
    def pinv(p):
        q=[0]*5
        for i in range(5): q[p[i]]=i
        return tuple(q)
    comms={mul(mul(a,b), mul(pinv(a),pinv(b))) for a in H for b in H}
    return subgroup(list(comms))
def solvable(H):
    cur=subgroup(list(H))
    while len(cur)>1:
        nxt=derived(cur)
        if len(nxt)==len(cur): return False
        cur=nxt
    return True
x = (1,2,3,4,0)  # 5-cycle
Sol = {y for y in A5 if solvable(subgroup([x,y]))}
# normal subgroups of A5 inside Sol: N normal, 1 < |N|, N subset Sol
def is_normal(N):
    Ns=set(N)
    def pinv(p):
        q=[0]*5
        for i in range(5): q[p[i]]=i
        return tuple(q)
    return all(mul(mul(g,h),pinv(g)) in Ns for g in A5 for h in N)
# candidate normal subgroups = subgroups generated by conjugacy-class unions; computationally: check all subgroups generated by elements of Sol
found_normal = False
for r in range(1, 4):
    for gens in itertools.combinations(sorted(Sol), r):
        H = subgroup(list(gens))
        if 1 < len(H) and H <= Sol and is_normal(H):
            found_normal = True; break
    if found_normal: break
print(f"[A.1] |A5|={len(A5)} |Sol(x)|={len(Sol)} (expected 10, D10) {ok(len(Sol)==10)}")
print(f"[A.1] nontrivial normal subgroup of A5 inside Sol n Sol: found={found_normal} -> REFUTED: {ok(not found_normal)}")

# ---------- 3. Graffiti 154: std dev of eigenvalues <= n / avg distance ; integer test 8 m W^2 > n^7 ----------
# lollipop K_72 + P_72  (clique vertices 0..71; path 72..143; path attached at vertex 0)
def lollipop(t,p):
    N=t+p; ad=[set() for _ in range(N)]
    for a in range(t):
        for b in range(a+1,t): ad[a].add(b); ad[b].add(a)
    prev=0
    for k in range(p):
        v=t+k; ad[prev].add(v); ad[v].add(prev); prev=v
    return ad
def wiener_and_m(ad):
    N=len(ad); W=0; m=sum(len(a) for a in ad)//2
    for s in range(N):
        dist={s:0}; q=[s]
        for v in q:
            for w in ad[v]:
                if w not in dist: dist[w]=dist[v]+1; q.append(w)
        W+=sum(dist.values())
    return W//2, m
ad=lollipop(72,72); N=144
W,m = wiener_and_m(ad)
lhs = 8*m*W*W
print(f"[154] lollipop(72,72): n={N} m={m} (claim 2628 {ok(m==2628)}) W={W} (claim 259080 {ok(W==259080)})")
print(f"[154] 8mW^2={lhs} > n^7={N**7}: {ok(lhs>N**7)} ; > n^5(n-1)^2={N**5*(N-1)**2}: {ok(lhs>N**5*(N-1)**2)}")
print(f"[154] VERDICT (std-dev reading, both conventions): REFUTED: {ok(lhs>N**7 and lhs>N**5*(N-1)**2)}")

# ---------- 4. Graffiti 143: variance of positive eigenvalues <= m / avg distance ----------
import numpy as np
def dumbbell(t1,p,t2):
    Nn=t1+p+t2; ad=[set() for _ in range(Nn)]
    for a in range(t1):
        for b in range(a+1,t1): ad[a].add(b); ad[b].add(a)
    off=t1+p
    for a in range(off,off+t2):
        for b in range(a+1,off+t2): ad[a].add(b); ad[b].add(a)
    chain=[0]+list(range(t1,t1+p))+[off]
    for u,v in zip(chain,chain[1:]): ad[u].add(v); ad[v].add(u)
    return ad
ad = dumbbell(20,8,20); Nn=48
W2,m2 = wiener_and_m(ad)
A = np.zeros((Nn,Nn))
for v in range(Nn):
    for w in ad[v]: A[v,w]=1.0
ev = np.linalg.eigvalsh(A)
assert min(abs(ev))>1e-8, "eigenvalue too close to 0 for sign classification"
pos = ev[ev>0]
var_pos = float(np.mean(pos**2) - np.mean(pos)**2)
rhs_n2   = m2*Nn*Nn/(2*W2)        # l = 2W/n^2 convention
rhs_pairs= m2*Nn*(Nn-1)/(2*W2)    # l = 2W/(n(n-1)) convention
print(f"[143] dumbbell(20,8,20): n={Nn} m={m2} W={W2} var_pos={var_pos:.6f}")
print(f"[143] var_pos > m/l (n^2 conv) {rhs_n2:.4f}: {ok(var_pos>rhs_n2)} ; (pairs conv) {rhs_pairs:.4f}: {ok(var_pos>rhs_pairs)}")
print(f"[143] VERDICT: REFUTED (both conventions): {ok(var_pos>rhs_n2 and var_pos>rhs_pairs)}")

# ---------- 5. Pandey parity: GP(9,2) not real-rooted (k even); GP(7,3) real-rooted (k odd) ----------
def gp(nn,k):
    ad={}
    for i in range(nn):
        ad.setdefault(('u',i),set()); ad.setdefault(('v',i),set())
    def link(a,b): ad[a].add(b); ad[b].add(a)
    for i in range(nn):
        link(('u',i),('u',(i+1)%nn)); link(('v',i),('v',(i+k)%nn)); link(('u',i),('v',i))
    verts=sorted(ad)
    idx={v:i for i,v in enumerate(verts)}
    return [set(idx[w] for w in ad[v]) for v in verts]
def indep_poly(ad):
    Nv=len(ad); coef=[0]*(Nv+1)
    order=list(range(Nv))
    def rec(i, chosen_mask_forbidden, count):
        coef[count]+=1
        for v in range(i, Nv):
            if not (chosen_mask_forbidden>>v)&1:
                nb=0
                for w in ad[v]: nb|=(1<<w)
                rec(v+1, chosen_mask_forbidden|(1<<v)|nb, count+1)
    rec(0,0,0)
    return coef
def trim(c):
    c=list(c)
    while len(c)>1 and c[-1]==0: c.pop()
    return c
c92 = trim(indep_poly(gp(9,2)))   # trailing zero coefficients above the independence number carry no information
claim92=[1,18,126,438,801,747,303,27]
c73 = trim(indep_poly(gp(7,3)))
claim73=[1,14,70,154,147,49]
r92 = np.roots(list(reversed(c92)))
r73 = np.roots(list(reversed(c73)))
nreal92 = int(np.sum(np.abs(r92.imag)<1e-7)); nreal73 = int(np.sum(np.abs(r73.imag)<1e-7))
maximag92 = float(np.max(np.abs(r92.imag)))
print(f"[GP] I(GP(9,2)) coeffs={c92} match claim: {ok(c92==claim92)}")
print(f"[GP] GP(9,2) real roots={nreal92}/7, max|imag|={maximag92:.4f} -> NOT real-rooted (k=2 even): {ok(nreal92<7 and maximag92>1e-3)}")
print(f"[GP] I(GP(7,3)) coeffs={c73} match claim: {ok(c73==claim73)}")
print(f"[GP] GP(7,3) real roots={nreal73}/5 -> real-rooted (k=3 odd): {ok(nreal73==5)}")
print(f"[GP] VERDICT: parity conjecture REFUTED both directions: {ok(c92==claim92 and nreal92<7 and c73==claim73 and nreal73==5)}")
