"""
Clean-room Gate-4 checker for the refutation of Conjecture A.16 of
arXiv:2412.16177 ("Mining Math Conjectures from LLMs: A Pruning Approach",
Chuharski, Rojas Collins, Meringolo).

Conjecture A.16 (verbatim, PDF v1, accessed 2026-06-11):
    "Let G be a non-solvable group. For any element x in G, if SolG(x) is a
     proper subgroup of G, then the intersection of SolG(x) with its
     normalizer in G is always metabelian."
where Sol_G(x) := {y in G | <x,y> is soluble}   (paper, Sec. 3.1).

Claimed counterexample: G = A5 x S4 (order 1440), x = ((0 1 2 3 4), id).
Claim: Sol_G(x) = D10 x S4 (order 240, a proper subgroup), N_G(Sol) = Sol,
hence Sol ∩ N_G(Sol) = D10 x S4, which has derived length 3 (second derived
subgroup = 1 x V4 != 1), hence is NOT metabelian. Conjecture refuted.

This checker was written from scratch, independently of the discovery code.
Everything is exact: permutations of {0..8} as integer tuples (A5 acts on
points 0-4, S4 on points 5-8). No external dependencies. Metabelian is taken
in its standard meaning: H is metabelian iff H'' = 1 (derived length <= 2).

Usage:  python checker.py [certificate.json]
Exit code 0 and final line "VERDICT: ... REFUTED" iff every check passes.
"""

import json
import os
import sys
from itertools import permutations

try:  # Windows consoles may default to cp1252
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

# ---------------------------------------------------------------- primitives

def compose(p, q):
    """(p*q)(i) = p(q(i)) — apply q first, then p."""
    return tuple(p[q[i]] for i in range(len(p)))

def inverse(p):
    r = [0] * len(p)
    for i, v in enumerate(p):
        r[v] = i
    return tuple(r)

def identity(n):
    return tuple(range(n))

def conj(g, h):
    """g h g^-1"""
    return compose(compose(g, h), inverse(g))

def comm(a, b):
    """[a,b] = a^-1 b^-1 a b"""
    return compose(compose(compose(inverse(a), inverse(b)), a), b)

def is_even(p):
    """parity of a permutation tuple (True = even)."""
    n = len(p)
    seen = [False] * n
    even = True
    for i in range(n):
        if not seen[i]:
            j, clen = i, 0
            while not seen[j]:
                seen[j] = True
                j = p[j]
                clen += 1
            if clen % 2 == 0:
                even = not even
    return even

# ------------------------------------------------------------- subgroup ops

def closure(gens):
    """Subgroup generated by gens (set of permutation tuples), by BFS on the
    right Cayley graph from the identity. Finite, so product-closure
    suffices (inverses appear as powers)."""
    gens = [g for g in gens]
    if not gens:
        raise ValueError("need at least one generator")
    n = len(gens[0])
    e = identity(n)
    S = {e}
    frontier = [e]
    while frontier:
        nxt = []
        for s in frontier:
            for g in gens:
                t = compose(s, g)
                if t not in S:
                    S.add(t)
                    nxt.append(t)
        frontier = nxt
    return S

def small_gens(H):
    """Greedy small generating set for a subgroup given as a full set."""
    n = len(next(iter(H)))
    e = identity(n)
    cur = {e}
    gens = []
    for h in sorted(H):           # deterministic order
        if h not in cur:
            gens.append(h)
            cur = closure(gens)
            if len(cur) == len(H):
                break
    assert cur == H or (len(H) == 1 and not gens), "small_gens failed"
    return gens if gens else [e]

def derived_subgroup(H):
    """[H,H] for H given as a full element set.
    [H,H] = normal closure in H of {[a,b] : a,b in gens(H)}; a set closed
    under conjugation by the generators is closed under conjugation by all
    of H, and the subgroup generated by a conjugation-closed set is normal.
    """
    gens = small_gens(H)
    n = len(next(iter(H)))
    e = identity(n)
    seed = {comm(a, b) for a in gens for b in gens}
    seed.discard(e)
    if not seed:
        return {e}
    # close the seed under conjugation by gens
    S = set(seed)
    frontier = list(seed)
    while frontier:
        nxt = []
        for s in frontier:
            for g in gens:
                t = conj(g, s)
                if t not in S:
                    S.add(t)
                    nxt.append(t)
        frontier = nxt
    return closure(S)

def derived_series(H):
    """Full derived series until fixpoint. Returns list [H, H', H'', ...]."""
    series = [H]
    while True:
        D = derived_subgroup(series[-1])
        if len(D) == len(series[-1]):
            break
        series.append(D)
        if len(D) == 1:
            break
    return series

def is_solvable(H):
    return len(derived_series(H)[-1]) == 1

def derived_length(H):
    """Derived length (only meaningful if solvable)."""
    s = derived_series(H)
    assert len(s[-1]) == 1, "derived_length called on non-solvable group"
    return len(s) - 1

def is_metabelian(H):
    """Standard definition: H'' = 1, i.e. derived length <= 2."""
    s = derived_series(H)
    return len(s[-1]) == 1 and (len(s) - 1) <= 2

def normalizer(Hset, Gset):
    """N_G(H). g normalizes H iff conj(g, gens(H)) ⊆ H (sizes equal)."""
    gens = small_gens(Hset)
    return {g for g in Gset if all(conj(g, h) in Hset for h in gens)}

def is_subgroup(S):
    """Direct pairwise product-closure test (independent of closure())."""
    n = len(next(iter(S)))
    if identity(n) not in S:
        return False
    return all(compose(a, b) in S for a in S for b in S)

# ------------------------------------------------------------------- checks

LOG = []
def log(msg):
    print(msg, flush=True)
    LOG.append(msg)

CHECK_N = [0]
def check(cond, msg):
    CHECK_N[0] += 1
    tag = "PASS" if cond else "FAIL"
    log(f"  [{tag}] check {CHECK_N[0]:2d}: {msg}")
    if not cond:
        log("VERDICT: CHECK FAILED — certificate rejected.")
        # flush log before dying
        write_log()
        sys.exit(1)

def write_log():
    d = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(d, "checker_run.log"), "w", encoding="utf-8") as f:
        f.write("\n".join(LOG) + "\n")

def perm_from_cycles(n, cycles):
    p = list(range(n))
    for cyc in cycles:
        for i, v in enumerate(cyc):
            p[v] = cyc[(i + 1) % len(cyc)]
    return tuple(p)

def main():
    d = os.path.dirname(os.path.abspath(__file__))
    cert_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(d, "certificate.json")
    with open(cert_path, encoding="utf-8") as f:
        cert = json.load(f)
    log(f"Certificate: {cert_path}")
    log(f"Conjecture:  {cert['conjecture_id']} of {cert['paper']}")
    log("")

    n = cert["n_points"]                      # 9
    e = identity(n)

    # ---- 0. self-tests of the group machinery on known cases -------------
    log("Step 0: machinery self-tests on known groups")
    a5g = [perm_from_cycles(5, [[0, 1, 2, 3, 4]]), perm_from_cycles(5, [[0, 1, 2]])]
    A5_5 = closure(a5g)
    check(len(A5_5) == 60, "|<(01234),(012)>| = 60 (= A5 on 5 points)")
    check(all(is_even(p) for p in A5_5), "all its elements are even")
    check(not is_solvable(A5_5), "A5 is NOT solvable (derived series stalls)")
    s4g = [perm_from_cycles(4, [[0, 1]]), perm_from_cycles(4, [[0, 1, 2, 3]])]
    S4_4 = closure(s4g)
    check(len(S4_4) == 24, "|<(01),(0123)>| = 24 (= S4 on 4 points)")
    ds = derived_series(S4_4)
    check([len(h) for h in ds] == [24, 12, 4, 1],
          "derived series of S4 has orders [24,12,4,1] (derived length 3)")
    check(not is_metabelian(S4_4), "S4 is not metabelian")
    A4_4 = derived_subgroup(S4_4)
    check(is_metabelian(A4_4), "A4 is metabelian (control: test can say yes)")
    log("")

    # ---- 1. build G = A5 x S4 on 9 points --------------------------------
    log("Step 1: build G")
    gens_G = [tuple(g) for g in cert["generators_G"]]
    G = closure(gens_G)
    check(len(G) == 1440, "|G| = 1440")
    # independent structural identification: G == { even perms of 0-4 } x { perms of 5-8 }
    prod = set()
    for a in permutations(range(5)):
        if not is_even(a):
            continue
        for b in permutations(range(5, 9)):
            prod.add(tuple(list(a) + list(b)))
    check(G == prod, "G equals {even perms of 0..4} x {all perms of 5..8} = A5 x S4")
    dsG = derived_series(G)
    check(len(dsG[-1]) > 1, f"G is non-solvable (derived series orders {[len(h) for h in dsG]})")
    x = tuple(cert["x"])
    check(x in G, f"x = {x} lies in G")
    check(x == perm_from_cycles(9, [[0, 1, 2, 3, 4]]),
          "x is the 5-cycle (0 1 2 3 4) with identity S4-part")
    log("")

    # ---- 2. brute-force Sol_G(x) over all 1440 elements -------------------
    log("Step 2: brute-force Sol_G(x) = {y : <x,y> soluble} over all 1440 y")
    solv_cache = {}
    Sol = set()
    subgroups_seen = 0
    for y in G:
        H = frozenset(closure([x, y]))
        if H not in solv_cache:
            solv_cache[H] = is_solvable(H)
            subgroups_seen += 1
        if solv_cache[H]:
            Sol.add(y)
    log(f"  distinct subgroups <x,y> encountered: {subgroups_seen}")
    check(len(Sol) == cert["claimed_sol_order"],
          f"|Sol_G(x)| = {len(Sol)} matches claimed {cert['claimed_sol_order']}")
    claimed_Sol = closure([tuple(g) for g in cert["claimed_sol_generators"]])
    check(len(claimed_Sol) == cert["claimed_sol_order"],
          "claimed generators generate a group of the claimed order (D10 x S4)")
    check(Sol == claimed_Sol, "brute-force Sol_G(x) == claimed D10 x S4 exactly")
    check(is_subgroup(Sol), "Sol_G(x) is a subgroup (direct pairwise closure test)")
    check(len(Sol) < len(G), "Sol_G(x) is PROPER (240 < 1440) — hypothesis of A.16 holds")
    check(e in Sol and x in Sol, "Sol contains 1 and x (sanity)")
    log("")

    # ---- 3. independent cross-check: subdirect lemma ----------------------
    log("Step 3: cross-check via projection (subdirect lemma)")
    # Sol_A5(a) inside A5 alone, with the SAME generic machinery
    a5 = perm_from_cycles(5, [[0, 1, 2, 3, 4]])
    SolA5 = {u for u in A5_5 if is_solvable(closure([a5, u]))}
    D10 = closure([a5, perm_from_cycles(5, [[1, 4], [2, 3]])])
    check(len(D10) == 10, "|<(01234),(14)(23)>| = 10 (= D10)")
    check(SolA5 == D10, "Sol_A5((01234)) == D10 (brute force over 60 elements)")
    NA5 = normalizer(D10, A5_5)
    check(NA5 == D10, "N_A5(D10) = D10 (D10 self-normalizing in A5)")
    # the lemma's prediction, verified pointwise against the brute force:
    # <(a,1),(u,v)> is solvable  iff  <a,u> is solvable in A5
    ok = all(((y in Sol) == is_solvable(closure([a5, tuple(y[i] for i in range(5))])))
             for y in G)
    check(ok, "for ALL 1440 y=(u,v): <x,y> soluble in G  <=>  <a,u> soluble in A5")
    log("")

    # ---- 4. normalizer and the intersection ------------------------------
    log("Step 4: N_G(Sol) and I = Sol ∩ N_G(Sol)")
    N = normalizer(Sol, G)
    check(N == Sol, "N_G(Sol_G(x)) = Sol_G(x) (self-normalizing), as claimed")
    I = Sol & N
    check(I == Sol, "I = Sol ∩ N_G(Sol) = Sol = D10 x S4 (order 240)")
    log("")

    # ---- 5. metabelian test on I ------------------------------------------
    log("Step 5: derived series of I — the kill")
    dsI = derived_series(I)
    orders = [len(h) for h in dsI]
    log(f"  derived series orders of I: {orders}")
    check(orders == cert["claimed_derived_orders_of_intersection"],
          f"orders match claimed {cert['claimed_derived_orders_of_intersection']}")
    check(len(dsI) >= 3 and len(dsI[2]) > 1,
          "second derived subgroup I'' is NON-trivial  =>  I is NOT metabelian")
    check(not is_metabelian(I), "is_metabelian(I) returns False")
    check(derived_length(I) == 3, "derived length of I is exactly 3")
    V4 = {e,
          perm_from_cycles(9, [[5, 6], [7, 8]]),
          perm_from_cycles(9, [[5, 7], [6, 8]]),
          perm_from_cycles(9, [[5, 8], [6, 7]])}
    check(dsI[2] == V4, "I'' = 1 x V4 exactly (the Klein four group on points 5-8)")
    log("")

    # ---- 6. robustness: alternative reading of 'its normalizer' ----------
    log("Step 6: alternative reading — 'its' = <x> rather than Sol_G(x)")
    Xgrp = closure([x])
    check(len(Xgrp) == 5, "<x> has order 5")
    Nx = normalizer(Xgrp, G)
    check(Nx == Sol, "N_G(<x>) = D10 x S4 = Sol — same set under either reading")
    I2 = Sol & Nx
    check(not is_metabelian(I2), "Sol ∩ N_G(<x>) is also NOT metabelian")
    log("")

    log("All checks passed.")
    log("VERDICT: Conjecture A.16 of arXiv:2412.16177 is REFUTED by "
        "G = A5 x S4, x = ((0 1 2 3 4), id): Sol_G(x) = D10 x S4 is a proper "
        "subgroup, Sol ∩ N_G(Sol) = D10 x S4 has derived length 3, not metabelian.")
    write_log()

if __name__ == "__main__":
    main()
