#!/usr/bin/env python3
"""
Clean-room Gate-4 checker: refutation of Conjecture A.1 of arXiv:2412.16177v1
("Mining Math Conjectures from LLMs: A Pruning Approach", Chuharski, Rojas
Collins, Meringolo; NeurIPS MathAI Workshop 2024).

Conjecture A.1 (verbatim, main.tex lines 445-447 of the arXiv v1 source; first
theorem-counter environment in appendix section A, hence numbered A.1 in the
compiled PDF; presented as "Example with no counterexamples from Claude"):

    Let G be a non-solvable group. For any two elements x, y in G, if
    Sol_G(x) \cap Sol_G(y) is non-empty, then Sol_G(x) \cap Sol_G(y)
    contains a non-trivial normal subgroup of G.

where (paper's Definition, section 2.2)  Sol_G(x) := { y in G : <x,y> is
soluble }, G a finite group.

CLAIMED REFUTATION (certificate): G = A5 (even permutations of {0,1,2,3,4}),
x = y = the 5-cycle (0 1 2 3 4).  Then Sol_G(x) = Sol_G(y) is a set of exactly
10 elements (the dihedral normalizer of <x>), the intersection is non-empty
(it contains 1 and x), yet it contains NO non-trivial normal subgroup of G,
because A5 is simple: the normal closure of every non-identity element of G is
all of G (order 60), which cannot fit inside a 10-element set.  A second pair
with x != y (y = x^2) is checked as well, in case "two elements" is read as
requiring distinct elements.

This checker recomputes EVERYTHING from first principles in exact integer/set
arithmetic (pure Python, no imports beyond json/sys/itertools, no floats, no
group-theory libraries) and validates the certificate JSON against the
recomputation.  Exit code 0 + "ACCEPT" iff every check passes; otherwise
nonzero + "REJECT: <reason>".

Written from scratch for Gate-4 clean-room verification, 2026-06-11.
No code was taken from the discovery-phase scripts.
"""

import itertools
import json
import sys

N = 5  # A5 acts on {0,1,2,3,4}
IDENT = tuple(range(N))

# Frozen verbatim statement (LaTeX source, arXiv:2412.16177v1 main.tex:446),
# whitespace-normalized.  The certificate must carry exactly this string.
FROZEN_STATEMENT = (
    "Let $G$ be a non-solvable group. For any two elements $x, y \\in G$, "
    "if $\\operatorname{Sol}_G(x) \\cap Sol_G(y)$ is non-empty, then "
    "$\\operatorname{Sol}_G(x) \\cap Sol_G(y)$ contains a non-trivial "
    "normal subgroup of $G$."
)

FROZEN_CONVENTION = (
    "G = A5 as the 60 even permutations of {0,1,2,3,4}; a permutation p is "
    "the tuple (p(0),...,p(4)); composition (p*q)(i) = p(q(i)); "
    "Sol_G(x) = {y in G : <x,y> is soluble}; soluble = derived series "
    "reaches the trivial group."
)

# Frozen provenance metadata (hardening after Codex referee audit
# 2026-06-11: auxiliary fields must not be silently tamperable).
FROZEN_DEFINITION = (
    "Let $G$ be a finite group. For any element $x \\in G$, the "
    "solubilizer of $x$ in $G$ is defined as: "
    "$\\operatorname{Sol}_G(x) := \\{ y \\in G \\mid \\langle x, y "
    "\\rangle \\text{ is soluble} \\}.$"
)
FROZEN_SOURCE_URL = "https://arxiv.org/abs/2412.16177"
FROZEN_SOURCE_VERSION = "v1 (only version; submitted 2024-12-09)"


def fail(reason):
    print("REJECT: " + reason)
    sys.exit(1)


# ----------------------------------------------------------------------
# Exact permutation-group primitives (integers and sets only).
# ----------------------------------------------------------------------

def compose(p, q):
    """(p*q)(i) = p(q(i))."""
    return tuple(p[q[i]] for i in range(N))


def inverse(p):
    inv = [0] * N
    for i in range(N):
        inv[p[i]] = i
    return tuple(inv)


def is_permutation(t):
    return isinstance(t, tuple) and len(t) == N and sorted(t) == list(range(N))


def parity(p):
    """0 = even, 1 = odd (inversion count mod 2)."""
    return sum(1 for i in range(N) for j in range(i + 1, N) if p[i] > p[j]) % 2


def closure(gens):
    """Subgroup generated by gens (finite group => positive words suffice)."""
    elems = {IDENT}
    frontier = [IDENT]
    gens = [g for g in gens]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                b = compose(a, g)
                if b not in elems:
                    elems.add(b)
                    nxt.append(b)
        frontier = nxt
    return frozenset(elems)


def derived_subgroup(H):
    """Commutator subgroup of the subgroup H (H given as a closed set)."""
    comms = set()
    for a in H:
        ai = inverse(a)
        for b in H:
            comms.add(compose(compose(ai, inverse(b)), compose(a, b)))
    return closure(comms)


def is_soluble(H):
    """Derived series reaches {e}?  (Exact fixpoint iteration.)"""
    cur = frozenset(H)
    while True:
        nxt = derived_subgroup(cur)
        if nxt == cur:
            return cur == frozenset({IDENT})
        cur = nxt


def solubilizer(G, x):
    """Sol_G(x) = {y in G : <x,y> soluble}, straight from the definition."""
    return frozenset(y for y in G if is_soluble(closure([x, y])))


def normal_closure(G, g):
    """Smallest normal subgroup of G containing g."""
    conjugates = {compose(compose(t, g), inverse(t)) for t in G}
    return closure(conjugates)


# ----------------------------------------------------------------------
# Certificate validation.
# ----------------------------------------------------------------------

def parse_perm(obj, label):
    if not isinstance(obj, list):
        fail("%s is not a list" % label)
    t = tuple(obj)
    if not all(isinstance(v, int) for v in t):
        fail("%s has non-integer entries" % label)
    if not is_permutation(t):
        fail("%s = %r is not a permutation of 0..%d" % (label, obj, N - 1))
    return t


def parse_perm_set(obj, label):
    if not isinstance(obj, list):
        fail("%s is not a list" % label)
    out = set()
    for k, entry in enumerate(obj):
        out.add(parse_perm(entry, "%s[%d]" % (label, k)))
    if len(out) != len(obj):
        fail("%s contains duplicates" % label)
    return frozenset(out)


def main(cert_path):
    with open(cert_path, "r", encoding="utf-8") as fh:
        cert = json.load(fh)

    # --- A. statement fidelity -------------------------------------------
    if cert.get("conjecture_statement_verbatim") != FROZEN_STATEMENT:
        fail("certificate statement does not match the frozen verbatim "
             "statement of Conjecture A.1 (arXiv:2412.16177v1)")
    if cert.get("conventions") != FROZEN_CONVENTION:
        fail("certificate conventions string does not match frozen conventions")
    if cert.get("solubilizer_definition_verbatim") != FROZEN_DEFINITION:
        fail("certificate solubilizer definition does not match the frozen "
             "verbatim definition (arXiv:2412.16177v1, Section 2.2)")
    if cert.get("source_url") != FROZEN_SOURCE_URL:
        fail("certificate source_url does not match frozen provenance")
    if cert.get("source_version") != FROZEN_SOURCE_VERSION:
        fail("certificate source_version does not match frozen provenance")

    # --- B. build G = A5 from first principles ---------------------------
    G = frozenset(p for p in itertools.permutations(range(N)) if parity(p) == 0)
    if len(G) != 60:
        fail("internal: |A5| != 60")
    # group axioms (closure under product and inverse; identity present)
    if IDENT not in G:
        fail("internal: identity not in A5")
    for a in G:
        if inverse(a) not in G:
            fail("internal: A5 not closed under inverse")
    sample_ok = all(compose(a, b) in G for a in G for b in G)
    if not sample_ok:
        fail("internal: A5 not closed under composition")

    # --- C. hypotheses of the conjecture ---------------------------------
    # G is finite (by construction) and must be non-solvable.
    if is_soluble(G):
        fail("G is soluble; hypothesis 'non-solvable group' violated")

    # --- D/E/F per certified pair (x, y) ----------------------------------
    pairs = cert.get("pairs")
    if not isinstance(pairs, list) or not pairs:
        fail("certificate has no pairs")

    for idx, pair in enumerate(pairs):
        tag = "pair[%d]" % idx
        x = parse_perm(pair.get("x"), tag + ".x")
        y = parse_perm(pair.get("y"), tag + ".y")
        if x not in G or y not in G:
            fail(tag + ": x or y is not an element of A5 (odd permutation)")

        sol_x_claimed = parse_perm_set(pair.get("sol_x"), tag + ".sol_x")
        sol_y_claimed = parse_perm_set(pair.get("sol_y"), tag + ".sol_y")
        inter_claimed = parse_perm_set(pair.get("intersection"),
                                       tag + ".intersection")

        # D. recompute the solubilizers from the paper's definition.
        sol_x = solubilizer(G, x)
        sol_y = solubilizer(G, y)
        if sol_x != sol_x_claimed:
            fail(tag + ": claimed Sol_G(x) does not match exact recomputation "
                 "(claimed %d elements, recomputed %d)"
                 % (len(sol_x_claimed), len(sol_x)))
        if sol_y != sol_y_claimed:
            fail(tag + ": claimed Sol_G(y) does not match exact recomputation")

        inter = sol_x & sol_y
        if inter != inter_claimed:
            fail(tag + ": claimed intersection does not match recomputation")
        if len(inter) != pair.get("intersection_order"):
            fail(tag + ": claimed intersection_order wrong")

        # E. the conjecture's hypothesis must HOLD (non-empty intersection).
        if IDENT not in inter:
            fail(tag + ": identity not in intersection (it must be; "
                 "<x,1> = <x> is cyclic hence soluble)")
        if not inter:
            fail(tag + ": intersection empty; conjecture hypothesis fails, "
                 "pair is not a counterexample")

        # F. the conjecture's CONCLUSION must FAIL:
        # no non-trivial normal subgroup of G inside the intersection.
        # F1 (direct): every non-identity g in the intersection has normal
        #     closure not contained in the intersection.  Any normal subgroup
        #     {e} != N <= intersection would contain some such g and hence
        #     its normal closure -- contradiction.
        for g in inter:
            if g == IDENT:
                continue
            ncl = normal_closure(G, g)
            if ncl <= inter:
                fail(tag + ": normal closure of %r IS contained in the "
                     "intersection -- conjecture conclusion holds here, "
                     "certificate does not refute it" % (g,))

        # F2 (simplicity certificate, independent route): A5 is simple --
        #     the normal closure of EVERY non-identity element is all of G,
        #     so the only non-trivial normal subgroup of G is G itself,
        #     and |G| = 60 > |intersection| forces non-containment.
        for g in G:
            if g == IDENT:
                continue
            if len(normal_closure(G, g)) != len(G):
                fail("simplicity check failed: normal closure of %r is proper"
                     % (g,))
        if len(inter) >= len(G):
            fail(tag + ": intersection is all of G; G itself is a "
                 "non-trivial normal subgroup inside it -- not a "
                 "counterexample")

        # G. optional structural sanity recorded in the certificate.
        if pair.get("sol_x_is_subgroup"):
            if closure(sol_x) != sol_x:
                fail(tag + ": certificate claims Sol_G(x) is a subgroup "
                     "but it is not closed")
        if pair.get("sol_x_order") is not None:
            if len(sol_x) != pair["sol_x_order"]:
                fail(tag + ": claimed sol_x_order wrong")
        if pair.get("sol_x_nonabelian"):
            ab = all(compose(a, b) == compose(b, a)
                     for a in sol_x for b in sol_x)
            if ab:
                fail(tag + ": certificate claims Sol_G(x) nonabelian "
                     "but it is abelian")

    # --- H. reading coverage (after the per-pair mathematics): require both
    # the x = y reading and the distinct-elements reading of "two elements"
    # to be certified, so neither interpretation of the quantifier survives.
    has_equal = any(tuple(p["x"]) == tuple(p["y"]) for p in pairs)
    has_distinct = any(tuple(p["x"]) != tuple(p["y"]) for p in pairs)
    if not has_distinct:
        fail("no certified pair with x != y; the distinct-elements reading "
             "of 'two elements' is not covered")
    if not has_equal:
        fail("no certified pair with x == y; the x = y reading is not "
             "covered")

    print("ACCEPT: Conjecture A.1 of arXiv:2412.16177v1 is REFUTED by the "
          "certified pair(s) in %s" % cert_path)
    print("  G = A5 (|G| = 60, non-solvable, simple: all 59 non-identity "
          "normal closures equal G).")
    for idx, pair in enumerate(pairs):
        print("  pair[%d]: |Sol(x)| = %d, |Sol(x) cap Sol(y)| = %d, "
              "non-empty, contains no non-trivial normal subgroup of G."
              % (idx, len(parse_perm_set(pair["sol_x"], "s")),
                 pair["intersection_order"]))
    return 0


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "certificate_a1_a5.json"
    sys.exit(main(path))
