"""Refined completeness check for the Lemma 6.2 case analyses.

The hand proofs first normalize B by the NAMED automorphisms (WLOG steps),
then intersect with the NAMED forts.  So the correct completeness criterion
is: for every 3-subset B, some image of B under the group generated by the
named automorphisms misses some named fort.  (Equivalently: B misses some
fort in the orbit of the named forts under that group.)

Also prints, for the strict check that failed, which 3-subsets intersect
all named forts directly, and confirms each is handled after normalization
exactly as the written cases dictate.
"""

from itertools import combinations

# S1: a1a2a3=0,1,2  b1b2b3=3,4,5  s=6
S1_E = [(0, 4), (0, 5), (1, 3), (1, 4), (1, 5), (2, 3), (2, 4), (2, 5),
        (6, 0), (6, 3)]
S1_N = 7
S1_FORTS = [frozenset(F) for F in
            ({1, 2}, {4, 5}, {0, 2, 6}, {3, 5, 6}, {0, 2, 3, 5})]
S1_AUTOS = [(0, 2, 1, 3, 4, 5, 6), (0, 1, 2, 3, 5, 4, 6)]

# S2: a1a2a3=0,1,2  b1b2b3=3,4,5  p=6  q=7
S2_E = [(0, 4), (0, 5), (0, 6), (1, 3), (1, 5), (1, 7),
        (2, 3), (2, 4), (2, 5), (6, 3), (7, 4)]
S2_N = 8
S2_FORTS = [frozenset(F) for F in
            ({0, 2, 6}, {1, 2, 7}, {3, 5, 6}, {4, 5, 7}, {0, 1, 3, 4},
             {0, 2, 3, 5}, {1, 2, 4, 5}, {0, 1, 6, 7}, {3, 4, 6, 7},
             {0, 2, 3, 7}, {0, 3, 5, 7})]
S2_AUTOS = [(3, 4, 5, 0, 1, 2, 6, 7), (1, 0, 2, 4, 3, 5, 7, 6)]


def group_closure(n, gens):
    ident = tuple(range(n))
    G = {ident}
    frontier = {ident}
    while frontier:
        new = set()
        for g in frontier:
            for h in gens:
                gh = tuple(h[g[i]] for i in range(n))
                if gh not in G:
                    new.add(gh)
        G |= new
        frontier = new
    return G


def run(name, n, forts, autos):
    G = group_closure(n, [tuple(a) for a in autos])
    print(f"{name}: |group generated by named automorphisms| = {len(G)}")
    orbit_forts = {frozenset(g[v] for v in F) for F in forts for g in G}
    print(f"{name}: named forts {len(forts)} -> orbit closure "
          f"{len(orbit_forts)}")
    holes = [S for S in combinations(range(n), 3)
             if all(set(S) & F for F in orbit_forts)]
    strict_holes = [S for S in combinations(range(n), 3)
                    if all(set(S) & F for F in forts)]
    print(f"{name}: 3-subsets meeting all named forts directly: "
          f"{strict_holes}")
    print(f"{name}: 3-subsets meeting all orbit-closed forts: {holes}")
    return not holes


ok1 = run("S1", S1_N, S1_FORTS, S1_AUTOS)
ok2 = run("S2", S2_N, S2_FORTS, S2_AUTOS)
print()
print("S1 case analysis complete under WLOG:", "PASS" if ok1 else "FAIL")
print("S2 case analysis complete under WLOG:", "PASS" if ok2 else "FAIL")
raise SystemExit(0 if ok1 and ok2 else 1)
